### ISSUE TITLE
where's Control.Applicative.Compat

### ISSUE THREAD

**Issue by simonmichael** [haskell-compat/base-compat#22]
0.8.0 dropped Control.Applicative.Compat. Where can this be found now ? (https://github.com/simonmichael/hledger/issues/245)

**Comment by sol** [comment]
The orphan instances are in `base-orphans` now.

Data types in general we dropped for now, as some of the data types that were added to `base` are already provided by other packages. Here is my stand on this https://github.com/haskell-compat/base-compat/issues/17#issuecomment-94228467. But I appreciated feedback.

**Comment by RyanGlScott** [comment]
Now that I think about it, I think we forgot to update the changelog to reflect this. It might not hurt to make a 0.8.0.1 release with `CHANGES.markdown` added to the `extra-source-files` section of the `.cabal` file to reduce confusion in the future.

**Comment by sol** [comment]
Damn! Yes, I missed that.  What do you think about linking to the changelog on github instead, for proper markdown formatting?

**Comment by RyanGlScott** [comment]
We could do both. I like having the changelog section of the Hackage page link to something, since that's where I usually look first to get an idea of what changed.

**Comment by sol** [comment]
Ok, cool, works for me. It's already late here, but I can update the changelog tomorrow, unless you want to take care of it.

**Comment by simonmichael** [comment]
I was using eg (<*) from Control.Applicative.Compat, which I don't think is in base-orphans ?

**Comment by RyanGlScott** [comment]
Ah. In that case, I think you are using `Control.Applicative.Compat` in a way we weren't quite intending. The purpose of `base-compat` is to provide a retrofitted version of `base` that exports functions whose implementations and type signatures match the most recent version of `base`, without requiring end users to use CPP pragmas to import it. As a result, we only export a `.Compat` module if there has been changes to functions in that module between versions of `base`.

In the case of `Control.Applicative`, nothing inside of the module (related to functions, at least) was changed in `base-4.8.0.0`, but rather, the `Applicative` typeclass was reexported from `Prelude`. Instead of doing something like this:

```haskell
#if !MIN_VERSION_base(4,8,0)
import Control.Applicative.Compat ((<*))
#endif
```

why not do this:

```haskell
import Prelude ()
import Prelude.Compat ((<*))
```

You get the same functionality with no CPP pragmas.

**Comment by sol** [comment]
No, but it's in Control.Applicative for all supported versions of base.  Control.Applicative.Compat did not define any functions nor operators. https://github.com/haskell-compat/base-compat/pull/21/files#diff-22b439017b3fdc587c4fd621f6c56078L1

**Comment by sol** [comment]
> why not do this:
> 
> import Prelude ()
> import Prelude.Compat
Yes, ignore my previous mail. This is what you want.

(Ryan, I edited your code in the quote and removed the import list for Prelude.Compat. That's what you meant, right?)

**Comment by simonmichael** [comment]
Yes, I was trying to keep things building before and after GHC 7.10. Clearly it's not as simple as "just use base-compat", Thanks for the hints

**Comment by RyanGlScott** [comment]
We definitely didn't advertise this change as well as we should have, given how substantial it was. (I uploaded `base-compat-0.8.0.1` with the changelog highlighted just in case.)

I'll go ahead and close this for now–please let us know if there are other issues in using `base-compat-0.8`.

**Comment by simonmichael** [comment]
All clear now, thank you.
