### ISSUE TITLE
Re-exports of unchanged modules?

### ISSUE THREAD

**Issue by bergmark** [haskell-compat/base-compat#45]
I'm finding it error-prone that I don't always know which modules have Compat variants defined and sometimes stray imports from base remain intact even though I need Compat. Especially when introducing base-compat into a project. I guess it could also introduce mistakes when upgrading to newer base-compat releases.

If base-compat had modules just re-export from base if unchanged it would make migration easier since I could (at least temporarily) drop the base dependency to make sure I don't leave any imports by accident.

I think this fits into base-compat since the existing modules already re-export unchanged functions from base.

What do you think?

**Comment by RyanGlScott** [comment]
I'm quite loathe to re-export modules entirely. There's been quite a few bugs with that feature of `Cabal`—notably, [Trac #12653](https://ghc.haskell.org/trac/ghc/ticket/12653).

**Comment by RyanGlScott** [comment]
Or maybe I misunderstood your question. Are you saying that `base-compat` should have a `.Compat` module for every single module in `base`?

**Comment by phadej** [comment]
Let's put this differently, are there a lot of modules yet without `.Compat` if `GHC` namespace is omitted?

There are also modules like `Type.Reflection` which probably doesn't make sense to make compat right now, but exhaustive list would be nice to see.

**Comment by bergmark** [comment]
My original thought was to have normal module re-exports `module Control.Applicative.Compat (module Control.Applicative)` but Cabal re-exports would be even better if we trusted them...

> Let's put this differently, are there a lot of modules yet without .Compat if GHC namespace is omitted?

There are roughly 50 base modules without Compat variants excluding GHC.*, another 85 with GHC.*.

My idea to drop the base dependency while migrating would only work if GHC.* was included though. For my projects I don't use much of it apart from GHC.Generics and GHC.SrcLoc, but that seems like a somewhat arbitrary shortcut...

But this gave me a better idea: How about a new package `base-compat-migrate` that does Cabal re-exports of only the remaining modules that you can switch to just to verify Compat imports? That way you just need to replace the base dep with that, add Compat where applicable, and revert to the base dep at the end. Then I wouldn't worry about re-export mishaps either since the dependency is not meant to stay in place.

**Comment by RyanGlScott** [comment]
I think part of the disconnect here is that you are trying to use `base-compat` as a wholesale replacement for `base`. Personally, I've never been of the opinion that `base-compat` should serve that role (although I've never gone and officially codified this belief in the `README` anywhere). The usual workflow is to only use imports from `base-compat` when you know you're in a situation when the corresponding import from `base` won't be backwards compatible. Later, if your project drops support for older versions of `base`, you can easily switch back to importing from `base` (and perhaps dropping the `base-compat` dependency altogether).

Your desire to just use `base-compat` for everything is understandable, but as noted earlier, it's nowhere near in a state where that is possible. If that were to change, I feel like we'd need to do some revamping of how the library is currently designed:

1. Currently, `base-compat` has the nice property that if a `.Compat` module exists, there is a pretty high chance it's actually backporting something on older versions of `base`. If we sync `base-compat` to use all the same modules as `base`, then this is no longer something you can rely on.

   A panacea would be to more clearly advertise which modules backport which things (which `base-compat` doesn't do a very good job of currently).
2. Moreover, some amount of work would need to go into actually keeping `base-compat` in sync with `base`'s modules. This would be awful to manually—it would be nice to automate this to some degree, similarly to how we (somewhat) [automate the creation of `.Repl` modules](https://github.com/haskell-compat/base-compat/blob/616b2aa249c4a433f020cb7c6f6e499c1bf5ec59/mk-repl-modules/MkReplModules.hs).

I'll reiterate that I don't want to pursue a `Cabal` reexport-based solution, since that's simply a no-go on certain versions of `Cabal`. The idea of creating a `base-compat-migrate` library is interesting, but I don't think it should go here.

**Comment by RyanGlScott** [comment]
@bergmark, is this issue still relevant now that [`base-compat-migrate`](http://hackage.haskell.org/package/base-compat-migrate) has been released?

**Comment by bergmark** [comment]
Yep, you beat me to it!

Seems to work nicely on the few projects I tried it on.
