### ISSUE TITLE
Add FiniteBits

### ISSUE THREAD

**Issue by aavogt** [haskell-compat/base-compat#5]
FiniteBits (https://github.com/ghc/packages-base/blob/master/Data/Bits.hs#L278) is new

**Comment by RyanGlScott** [comment]
One possible hiccup with backporting `FiniteBits` is that the class changed between `base-4.7.0.0` and `base-4.8.0.0`. In `base-4.7.0.0`, it only had one class function:

```haskell
class Bits b => FiniteBits b where
    finiteBitSize :: b -> Int
```

whereas in `base-4.8.0.0`, it has three functions (with a minimally complete definition of `finiteBitSize`):

```haskell
class Bits b => FiniteBits b where
    finiteBitSize :: b -> Int

    countLeadingZeros :: b -> Int
    countLeadingZeros = ...

    countTrailingZeros :: b -> Int
    countTrailingZeros = ...
```

If we backport the `base-4.8.0.0` definition, then any users who override `countLeadingZeros` or `countTrailingZeros` would have their code break with `base-4.7.0.0`.

To get around this, we could backport the `base-4.7.0.0` definition and define `countLeadingZeros` and `countTrailingZeros` as separate functions with their default definitions. This way, you could still use all of the `FiniteBits` functionality on all versions of `base`, and if you wanted to, you could override `countLeadingZeros` or `countTrailingZeros` only on `base` >= 4.8.0.0 (although doing so would require CPP pragmas).

**Comment by sol** [comment]
@RyanGlScott I think I agree with that approach, backporting the `base-4.7.0.0` version.

**Comment by RyanGlScott** [comment]
I'm going to close this as "wontfix" for now, since we've decided to include only reexports and redefined functions in `base-compat`, not redefined data types or typeclasses (see [this discussion](https://github.com/haskell-compat/base-compat/issues/17)). Our motivation for this is to avoid issues that arise when the API for data types or typeclasses change, as is evidenced with `FiniteBits`. This approach makes `base-compat` as uncontroversial as possible.

If backporting `FiniteBits` is mission-critical to you, feel free to reopen this bug.
