### ISSUE TITLE
move System.Environment.Compat features to base-compat-batteries

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-compat#59]
So `base-compat` could drop dependency on `unix`.

Dependency on `unix` makes harder to upgrade `time`.

**Comment by RyanGlScott** [comment]
I'm afraid I don't know what the phrase "makes harder to upgrade `time`" means in this context.

Admittedly, the only that `base-compat` depends on `unix` is because `unix` is shipped directly with GHC itself. Nevertheless, I'm reluctant to introduce a breaking change like this without a good reason, and I'm not convinced yet that there is a good reason.

**Comment by phadej** [comment]
I'm ok that this change is included when there are other breaking changes.

Seems even without `unix` dependency I run with a problem when `doctest` is in build-plan; so I guess `time` is simply unupgradeable in any complex enough (and test-rich) environment
