### ISSUE TITLE
Inline setenv

### ISSUE THREAD

**Issue by sol** [haskell-compat/base-compat#6]

**Comment by RyanGlScott** [comment]
I noticed that the implementations of `setEnv` and `unsetEnv` are different in [`base`](https://ghc.haskell.org/trac/ghc/attachment/ticket/7427/0001-Add-setEnv-unsetEnv-to-System.Environment.patch) and in [`setenv`](https://github.com/sol/setenv/blob/e871295f556ed25b73bea24184725c5a74a221e3/src/System/SetEnv.hs#L61-113)—I take it we'd want to inline the code from `base`? If so, do we want to use the `configure` script from `base` to properly detect `unsetEnv`'s behavior? If we do, it'll make things a bit more complicated on Windows.

**Comment by sol** [comment]
Hm, not sure, but I think I'd rather have the `unix` or `setenv` dependency then a configure script.

**Comment by RyanGlScott** [comment]
Well, that does go against the ideal of having no dependencies other than `base`... but I agree that `configure` scripts are less than desirable. Alternatively, we could remove `setEnv`/`unsetEnv` functionality from `base-compat` entirely and move all of the icky stuff from `base` into the `setenv` package. That way, we wouldn't have to force Windows users to install `base-compat` with Cygwin/MSYS.

**Comment by sol** [comment]
From my perspective it would be good to have it in `base-compat`.

The thing is that `unix` comes with GHC, so I kind of assumed it's a "free" dependency.  But it's cabal installable, so users could install a newer version, which means `unix` can contribute to cabal dependency hell and is not for "free".

Not sure what to do here.  Ideally we would be able to provide that functionality without a configure script nor the `unix` dependency.  I haven't looked into it.  @RyanGlScott did you reach the point where you were confident that this can't possibly work?

**Comment by RyanGlScott** [comment]
Using a `configure` script isn't impossible _per se_ on Windows, but you'd have to use Cygwin/MSYS to install the package (which is not something most novice Haskell users would think of). The `network` package, which notably uses a `configure` script, is annoying enough to install for most Windows users that they bundled a prebuilt version of it with [`minghc`](https://github.com/fpco/minghc).

On the other hand, I don't think we'd be able to duplicate the functionality of `unsetEnv` from `base` exactly without a `configure` script, since the `base` implementation of `unsetEnv` throws an error if `unsetenv` returns a nonzero value, but some OSes' `unsetenv` return `void` instead of `int`. Thus, we could avoid `configure` by having `__hsbase_unsetenv` always return 0, but then we'd lose the ability to handle errors.

Thus, I'd say it comes down to a choice between accuracy and convenience. If you want a fully backwards-compatible implementation, we'd probably have to use either a `configure` script or a `unix` dependency. If you want the most amount of users to be able to install `base-compat`, we could implement a slightly off-spec version of `unsetEnv`.

Personally, I'd argue that having a `unix` dependency is not such a bad thing. After all, it is a GHC boot library, so all POSIX versions of GHC should have it. We can use the `cabal` flag `if os(windows)` to ensure that it's not a dependency for Windows users, and use [the CPPed definition](http://hackage.haskell.org/package/base-4.8.0.0/docs/src/System-Environment.html#unsetEnv) from `base` with little trouble. However, I'll leave the final decision to you, since you'd probably be using this functionality more than I would.

**Comment by sol** [comment]
I would like to neglect the option of adding a `configure` script.  A criteria that I apply to judge whether something is viable or not is whether I would `base-compat` as a dependency on e.g. `hspec`.  A `configure` script is definitely a k.o. criteria for me.  So if I don't even want to use it, I don't see how the package could be useful to others.

With the other two options, I would be fine with either.  But I'm not sure whether we have the bandwidth to test all the unixes that users may encounter in the wild.  So I think I agree with depending on `unix`, at least for now.

**Comment by sol** [comment]
I guess that would mean we can use the code from `setenv` verbatim.

**Comment by RyanGlScott** [comment]
Works for me!

Also, it looks like there may be a very slight difference in the way that `setEnv` from `base` and `setenv` work at the moment: it appears that [`base`'s version](http://hackage.haskell.org/package/base-4.8.0.0/docs/src/System-Environment.html#line-271) performs a check for improperly formatted input, whereas [`setenv`'s version](https://github.com/sol/setenv/blob/e871295f556ed25b73bea24184725c5a74a221e3/src/System/SetEnv.hs#L61-82) doesn't seem to do this.

**Comment by sol** [comment]
We have extensive tests in https://github.com/sol/setenv/blob/master/test/System/SetEnvSpec.hs, and at least as far as the tests cover the observable behavior they are the same.  That is good enough for me.

Ian Lynagh modified my original patch for base back then for some reason.  Can't remember the details.

**Comment by sol** [comment]
Hmm, I guess it may behave different on unixes where the underlying C functions have a void exit code, as you noted earlier.  But that would also mean that `unix` behaves different on different platforms, not sure.

**Comment by RyanGlScott** [comment]
Well, you certainly know a lot more about `setenv` than I do, so I'll trust you on that.

`unix` also has a `configure` script and [changes the implementation](https://github.com/haskell/unix/blob/94d8824bae10c9d91f56c1aee9c45a90136a1770/System/Posix/Env.hsc#L118-128) of `unsetEnv` depending on the return type of C's `unsetenv`, so there shouldn't be any discrepancies resulting from using `unsetEnv` from `unix`.
